import { writeFileSync } from 'node:fs'
import { genome, genomeKey, levelFromXp, visualKey } from '@nibbl/core'
import { BOTS, totalXpForLevel } from '../src/bots'

const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const seenGenome = new Set<string>()
const seenVisual = new Set<string>()
const lines = [
  '-- Generated by scripts/gen-bot-migration.ts from src/bots.ts. Do not edit by hand.',
  '-- 12 seeded bots (decision 0009). Re-run `pnpm gen:bots` as a NEW migration if core keys change.',
]

for (const b of BOTS) {
  const g = genome(b.seed, b.tier, b.shiny)
  const key = genomeKey(g)
  const visual = visualKey(g)
  if (seenGenome.has(key) || seenVisual.has(visual)) throw new Error(`bot ${b.serial} looks like another bot; change its seed`)
  seenGenome.add(key)
  seenVisual.add(visual)
  const xp = totalXpForLevel(b.level) + b.extraXp
  if (levelFromXp(xp).level !== b.level) throw new Error(`bot ${b.serial}: extraXp ${b.extraXp} spills past level ${b.level}`)
  lines.push(
    `INSERT INTO pets (serial, machine_hash, token_hash, seed, genome_key, visual_key, tier, shiny, genesis, name, label, xp, level, is_bot, hatched_at, last_sync_at) VALUES (${b.serial}, ${q(`bot:${b.serial}`)}, 'bot:disabled', ${g.seed}, ${q(key)}, ${q(visual)}, ${q(b.tier)}, ${b.shiny ? 1 : 0}, ${b.genesis ? 1 : 0}, ${q(b.name)}, ${q(b.label)}, ${xp}, ${b.level}, 1, ${b.hatchedAt}, ${b.hatchedAt});`,
  )
}
lines.push(`UPDATE counters SET value = ${Math.max(...BOTS.map(b => b.serial))} WHERE name = 'serial';`)

writeFileSync(new URL('../migrations/0002_seed_bots.sql', import.meta.url), `${lines.join('\n')}\n`)
console.log(`wrote ${BOTS.length} bots to migrations/0002_seed_bots.sql`)
